### ISSUE TITLE
Connecting to a RESTful backend API

### ISSUE THREAD

**Issue by fullofcaffeine** [DoclerLabs/hexMachina#96]
Hi there,

hexMachina looks interesting!

I'm used to modelling my apps around RESTful concepts, and I have a question regarding commands. It seems overkill to create a command per verb for a restful entity provided by a backend API. Let's take the photo gallery example. We have a `LoadPhotosCommand` to load the photos, which in RESTful terms is basically the index or GET action on the entity itself.

Having a command class per verb method is just overkill in my opinion. I'd rather have controller would provide the right `list/search`, `create`, `show`, `update`, `destroy` methods or equivalent? 

I'm not sure how this would fit within hexMachina's architecture or if such support is planned soon? Any suggestions appreciated. I'm probably also misunderstanding the architecture of the framework.

Of course, I'm sure I can ditch commands and add my own layer there, but I'd rather check the author's thoughts before proceeding :)

As reference, take a look at EmberJS's REST Adapter, which makes it very easy to connect Ember to a RESTful API: https://guides.emberjs.com/v1.10.0/models/the-rest-adapter/.

**Comment by grosmar** [comment]
Hello,

Thanks for the nice words :)

**Let me to answer short first:**
Yes, we have also a solution with Controllers. Check out the other example of the FlickR with a new way, where we use Controller and Commands mixed: https://github.com/DoclerLabs/hexMachina-Gallery-Experimental-MDVC/blob/master/src/example/module/gallery/controller/GalleryController.hx

**And let's have the long answer:**
Be believe in MVC structuring, but it can have many type of implementations. For the C, Controller layer we used first the [Command pattern](https://en.wikipedia.org/wiki/Command_pattern), because of a lot of reasons:
- Help people to ensure to not store states in the Commands, and use instead the Model, that is designed for it, because the Commands are dead at the end of the run.
- Help really separate functionalities and keep focus on [Signle Responsibility](https://en.wikipedia.org/wiki/Single_responsibility_principle)
- Support reusability. With commands you can reuse the same business logic that you created in other situations, without depending on all the other irrelevant things. If you have for example a monolith Controller that is also responsible gallery images user login, it will cause strange dependencies when you just want to get a list of pictures from some other part of your application
- With Macros (see [Diagram](http://hexmachina.org/design/2016/05/06/module-event-mechanism.html for an example) you can chain multiple commands in sequence, parallel, etc, so you have the power to control your workflow inside the application.

By the time, we also realized in many cases you want to group many similar commands in one class to give easy access to these functionalities easily, less verbose (like you said `list/search`, `create`, `show`, ...)
And by the time it was also a complain from some people making a lot of classes for just simple things is an overkill. 

So that's why we implemented the Controller concept, that makes much less verbose and faster communication between the different layers, focusing only writing the business logic, not wasting time with verbosity.

**Let me to add some extra toughts:**
- We still believe you will not have problems with creating a lot of classes, but with using the right architectural decisions, to keep your code modular, and reusable, that you can rely on after in your second project, and not just start everything from scratch all the time. 
- You can have Controller class, but we believe when it comes to complexity and multiple private functions, long ones in your controller you are better to separate it into a different Command, and call it from the Controller (like in the example above)
- As you can see hexMachina if fully technological independent. We don't rely on any platform or solution, so in the core we don' t have at this moment such an adapter that is reading from any socket or technologic-dependent protocol. But we are open for creating more and more libraries for the framework, that makes easier life in different platforms. So if you'll have a nice solution we warmly welcome to add it to the list of [Libraries](http://hexmachina.org/docs/tools/) on our website.

**Comment by fullofcaffeine** [comment]
Thanks, that's very helpful.

I'm looking at using hexMachina as the frontend (targetting js) framework of a web/mobile app. The backend will be Ruby on Rails. 

How well does hexMachina support the javascript target? 

Since it's going to be a web app, there will be frontend templates. I'm looking into using https://github.com/pugjs/pug, which is similar to the excellent `slim-template` (ruby). Does hexMachina have any concept of templates as of now? The view class would probably need to render these templates. I have a few ideas inspired by Angular and Ember but would like to check with you as well.

And lastly, does it provide any kind of routing/dispatcher to handle URLs?

**Comment by grosmar** [comment]
Javascript target is the most tested and tried target, next to flash, so I can strongly recommend to use it. 

For templating we plan to have our library in the upcoming few months, but till then as you see it's compatible with any templating system. And you're right, you need to render the templates in your view layer. Later we want to have better integration with data binding and other juicy things, actually we would like to support more and more reactive style programming, to let developers focus on the real business expressions.

No routing library at this moment as it would be a platform dependent concept like templating, but you can post a proposal on github for it and we try to fit in our roadmap later.

**Comment by fullofcaffeine** [comment]
Great Balázs! Thanks a lot for taking the time to answer.

I'll build a POC app to learn a bit more about hexMachina. I'm very
interested in using it for web development, specifically frontend for now,
maybe backend services later.

Keep up the great work!

**Comment by grosmar** [comment]
Your welcome!

I'm happy you are interested :)
Feel free to ask if you have any questions. I know we need to improve a lot in documentation, we are working on it, till then you can rely on example applications.

I'm also working on one now, but still not finished: https://github.com/grosmar/hexMachina-TicTacToe
